In [1]:
!pip install pandas

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [9]:
import pandas as pd

In [10]:
df= pd.read_csv('Car Insurance.csv')

In [11]:
df=pd.read_csv(r'C:\Users\admin\Desktop\MLDM\Week 2\Car Insurance.csv')

# Alternative method: Instead of uploading the dataset to the notebook’s directory, you can load the dataset to a Data Frame from its location using the following code:
df = pd.read_csv (r'Path where the CSV file is stored\File name.csv'

In [12]:
df

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

# We can use row and column indices to show the content of a cell. In addition, we can callthe column name to return a python series. DataFrame.iloc[row,col] shows the value of denoted element

In [13]:
df.iloc[:,:]

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

# Showing the first column

In [14]:
df.iloc[:,0]

0    Toyota
1      Ford
2    Toyota
3    Nissan
4    Nissan
5      Ford
6    Toyota
7    Nissan
8    Toyota
9    Nissan
Name: Make, dtype: object

# Showing the second row

In [7]:
df.iloc[1]

Make          Ford
Age            4.0
Mileage    30500.0
Fuel             P
Gearbox          M
Colour       Black
Claimed        Yes
Name: 1, dtype: object

# Calling the third element of the first column

In [8]:
df.iloc[2,0]

'Toyota'

# Returning the Age column

In [9]:
df.iloc[:,1]

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [10]:
df['Age']

0     2.0
1     4.0
2    15.0
3    13.0
4     2.0
5     8.0
6     NaN
7    20.0
8    13.0
9     7.0
Name: Age, dtype: float64

In [11]:
df.Colour

0      Red
1    Black
2    White
3    White
4    Black
5    Green
6      NaN
7    Green
8     Blue
9    Black
Name: Colour, dtype: object

# Listing the unique values of the first column

In [13]:
df.iloc[:,0].unique()

array(['Toyota', 'Ford', 'Nissan'], dtype=object)

# Counting each value in the frist column

In [15]:
df.iloc[:,0].value_counts()

Make
Toyota    4
Nissan    4
Ford      2
Name: count, dtype: int64

# Checking where (in which rows) ‘Nissan’ exists in the first column?

In [15]:
df.iloc[:,0].isin(['Nissan'])

0    False
1    False
2    False
3     True
4     True
5    False
6    False
7     True
8    False
9     True
Name: Make, dtype: bool

# Sorting ascendingly the data frame based on values of the second column

In [16]:
df.iloc[:,1].sort_values(ascending=False)

7    20.0
2    15.0
3    13.0
8    13.0
5     8.0
9     7.0
1     4.0
0     2.0
4     2.0
6     NaN
Name: Age, dtype: float64

# Checking whether the second column has any null value

In [16]:
df.iloc[:,1].isnull().values.any()

True

In [18]:
df.iloc[:,1].min()

2.0

In [19]:
df['Age'].max()

20.0

In [20]:
df['Age'].mean()

9.333333333333334

# Missing Values

In [21]:
df.iloc[:,:]

Make   Age   Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.0   27000.0    P       A    Red     Yes
1    Ford   4.0   30500.0    P       M  Black     Yes
2  Toyota  15.0  120000.0    D       A  White      No
3  Nissan  13.0   53000.0    D       M  White      No
4  Nissan   2.0       NaN    D       M  Black      No
5    Ford   8.0   73000.0  NaN       M  Green      No
6  Toyota   NaN  138000.0    P       M    NaN     Yes
7  Nissan  20.0   38000.0    D     NaN  Green     Yes
8  Toyota  13.0   67000.0    D       A   Blue      No
9  Nissan   7.0   36000.0    P       M  Black     Yes

# Checking which columns contain null values.

In [17]:
df.isnull().sum()

Make       0
Age        1
Mileage    1
Fuel       1
Gearbox    1
Colour     1
Claimed    0
dtype: int64

In [19]:
!pip install scikit-learn

In [5]:
from sklearn.impute import SimpleImputer

# As Age and Mileage are numerical and contain null values, we can use SimpleImputer to estimate the null value. 

In [20]:
# numerical variable
#Strategies: mean, median, most_frequent, constant

import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='mean')
numImputer = numImputer.fit(df[['Age', 'Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr
                                   

array([[2.00000000e+00, 2.70000000e+04],
       [4.00000000e+00, 3.05000000e+04],
       [1.50000000e+01, 1.20000000e+05],
       [1.30000000e+01, 5.30000000e+04],
       [2.00000000e+00, 6.47222222e+04],
       [8.00000000e+00, 7.30000000e+04],
       [9.33333333e+00, 1.38000000e+05],
       [2.00000000e+01, 3.80000000e+04],
       [1.30000000e+01, 6.70000000e+04],
       [7.00000000e+00, 3.60000000e+04]])

In [21]:
# numerical variable
#Strategies: mean, median, most_frequent, constant

import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='median')
numImputer = numImputer.fit(df[['Age', 'Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr
                              

array([[2.00e+00, 2.70e+04],
       [4.00e+00, 3.05e+04],
       [1.50e+01, 1.20e+05],
       [1.30e+01, 5.30e+04],
       [2.00e+00, 5.30e+04],
       [8.00e+00, 7.30e+04],
       [8.00e+00, 1.38e+05],
       [2.00e+01, 3.80e+04],
       [1.30e+01, 6.70e+04],
       [7.00e+00, 3.60e+04]])

In [22]:
# numerical variable
#Strategies: mean, median, most_frequent, constant

import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
numImputer = numImputer.fit(df[['Age', 'Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr
                              

array([[2.00e+00, 2.70e+04],
       [4.00e+00, 3.05e+04],
       [1.50e+01, 1.20e+05],
       [1.30e+01, 5.30e+04],
       [2.00e+00, 2.70e+04],
       [8.00e+00, 7.30e+04],
       [2.00e+00, 1.38e+05],
       [2.00e+01, 3.80e+04],
       [1.30e+01, 6.70e+04],
       [7.00e+00, 3.60e+04]])

In [32]:
# numerical variable
#Strategies: mean, median, most_frequent, constant

import numpy as np
numImputer = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value=-1)
numImputer = numImputer.fit(df[['Age', 'Mileage']])
new_serr=numImputer.transform(df[['Age', 'Mileage']])
new_serr
                              

array([[ 2.00e+00,  2.70e+04],
       [ 4.00e+00,  3.05e+04],
       [ 1.50e+01,  1.20e+05],
       [ 1.30e+01,  5.30e+04],
       [ 2.00e+00, -1.00e+00],
       [ 8.00e+00,  7.30e+04],
       [-1.00e+00,  1.38e+05],
       [ 2.00e+01,  3.80e+04],
       [ 1.30e+01,  6.70e+04],
       [ 7.00e+00,  3.60e+04]])

# For the categorical variables the most frequent and constant strategies are applicable

In [37]:
# categorical variables
#strategies: most_frequent, constant
catImputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
catImputer = catImputer.fit(df[['Fuel','Gearbox','Colour']])
new_serr=catImputer.transform(df[['Fuel','Gearbox','Colour']])
new_serr

array([['P', 'A', 'Red'],
       ['P', 'M', 'Black'],
       ['D', 'A', 'White'],
       ['D', 'M', 'White'],
       ['D', 'M', 'Black'],
       ['D', 'M', 'Green'],
       ['P', 'M', 'Black'],
       ['D', 'M', 'Green'],
       ['D', 'A', 'Blue'],
       ['P', 'M', 'Black']], dtype=object)

In [39]:
# categorical variables
#strategies: most_frequent, constant
catImputer = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='Red')
catImputer = catImputer.fit(df[['Fuel','Gearbox','Colour']])
new_serr=catImputer.transform(df[['Fuel','Gearbox','Colour']])
new_serr

array([['P', 'A', 'Red'],
       ['P', 'M', 'Black'],
       ['D', 'A', 'White'],
       ['D', 'M', 'White'],
       ['D', 'M', 'Black'],
       ['Red', 'M', 'Green'],
       ['P', 'M', 'Red'],
       ['D', 'Red', 'Green'],
       ['D', 'A', 'Blue'],
       ['P', 'M', 'Black']], dtype=object)

In [23]:
# All together
numImputer = SimpleImputer(missing_values=np.nan, strategy='mean')
numImputer = numImputer.fit(df[['Age', 'Mileage']])
df[['Age', 'Mileage']]=numImputer.transform(df[['Age', 'Mileage']])
catImputer = SimpleImputer(missing_values=np.nan, strategy= 'most_frequent')
catImputer = catImputer.fit(df[['Fuel','Gearbox', 'Colour']])
df[['Fuel', 'Gearbox', 'Colour']]=catImputer.transform(df[['Fuel', 'Gearbox', 'Colour']])
df

Make        Age        Mileage Fuel Gearbox Colour Claimed
0  Toyota   2.000000   27000.000000    P       A    Red     Yes
1    Ford   4.000000   30500.000000    P       M  Black     Yes
2  Toyota  15.000000  120000.000000    D       A  White      No
3  Nissan  13.000000   53000.000000    D       M  White      No
4  Nissan   2.000000   64722.222222    D       M  Black      No
5    Ford   8.000000   73000.000000    D       M  Green      No
6  Toyota   9.333333  138000.000000    P       M  Black     Yes
7  Nissan  20.000000   38000.000000    D       M  Green     Yes
8  Toyota  13.000000   67000.000000    D       A   Blue      No
9  Nissan   7.000000   36000.000000    P       M  Black     Yes

# Categorical Data

To convert categorical features to integer codes, the OrdinalEncoder is an option

In [29]:
from sklearn import preprocessing
enc = preprocessing.OrdinalEncoder()
enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour', 'Claimed']])

array([[2., 1., 0., 3., 1.],
       [0., 1., 1., 0., 1.],
       [2., 0., 0., 4., 0.],
       [1., 0., 1., 4., 0.],
       [1., 0., 1., 0., 0.],
       [0., 0., 1., 2., 0.],
       [2., 1., 1., 0., 1.],
       [1., 0., 1., 2., 1.],
       [2., 0., 0., 1., 0.],
       [1., 1., 1., 0., 1.]])

In [30]:
enc= preprocessing.OneHotEncoder(drop='first')
enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour', 'Claimed']]).toarray()

array([[0., 1., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 1.]])

In [31]:
enc.categories_

[array(['Ford', 'Nissan', 'Toyota'], dtype=object),
 array(['D', 'P'], dtype=object),
 array(['A', 'M'], dtype=object),
 array(['Black', 'Blue', 'Green', 'Red', 'White'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

# Now the data can be normalized since it does not have any null values (standardization) using StandardScaler

# To convert all variables in the dataset

In [33]:
# All together

# target variable, it just uses the ordinal encoder
enc= preprocessing.OrdinalEncoder()
df['Claimed']=enc.fit_transform(df['Claimed'].values.reshape(-1,1))

#input variables one hot encoding
enc= preprocessing.OneHotEncoder(drop='first')
onehots = enc.fit_transform(df[['Make', 'Fuel', 'Gearbox', 'Colour']]).toarray()
# creating the new df
cols = []
for i in enc.categories_:
    i = np. delete(i,0)
    cols.extend(i)
df= df.join(pd.DataFrame(onehots, columns=cols))

df= df.drop(['Make', 'Fuel', 'Gearbox', 'Colour'], axis=1)

In [34]:
df

Age        Mileage  Claimed  Nissan  Toyota    P    M  Blue  Green  \
0   2.000000   27000.000000      1.0     0.0     1.0  1.0  0.0   0.0    0.0   
1   4.000000   30500.000000      1.0     0.0     0.0  1.0  1.0   0.0    0.0   
2  15.000000  120000.000000      0.0     0.0     1.0  0.0  0.0   0.0    0.0   
3  13.000000   53000.000000      0.0     1.0     0.0  0.0  1.0   0.0    0.0   
4   2.000000   64722.222222      0.0     1.0     0.0  0.0  1.0   0.0    0.0   
5   8.000000   73000.000000      0.0     0.0     0.0  0.0  1.0   0.0    1.0   
6   9.333333  138000.000000      1.0     0.0     1.0  1.0  1.0   0.0    0.0   
7  20.000000   38000.000000      1.0     1.0     0.0  0.0  1.0   0.0    1.0   
8  13.000000   67000.000000      0.0     0.0     1.0  0.0  0.0   1.0    0.0   
9   7.000000   36000.000000      1.0     1.0     0.0  1.0  1.0   0.0    0.0   

   Red  White  
0  1.0    0.0  
1  0.0    0.0  
2  0.0    1.0  
3  0.0    1.0  
4  0.0    0.0  
5  0.0    0.0  
6  0.0    0.0  
7  0.0    0.0  
8  0.0    0.0  
9  0.0    0.0

# The Standardization is successful since our dataset does not have any null value. 

Normalization operation can be carried out using the STANDARDSCALER utility class for preprocessing

In [35]:
from sklearn import preprocessing

x = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

In [38]:
scaler = preprocessing.StandardScaler().fit(x)

In [39]:
scaler.mean_

array([9.33333333e+00, 6.47222222e+04, 5.00000000e-01, 4.00000000e-01,
       4.00000000e-01, 4.00000000e-01, 7.00000000e-01, 1.00000000e-01,
       2.00000000e-01, 1.00000000e-01])

In [40]:
scaler.scale_

array([5.62138773e+00, 3.57345149e+04, 5.00000000e-01, 4.89897949e-01,
       4.89897949e-01, 4.89897949e-01, 4.58257569e-01, 3.00000000e-01,
       4.00000000e-01, 3.00000000e-01])

In [41]:
X_scaled = scaler.transform(x)

In [45]:
X_scaled

array([[-1.30454146e+00, -1.05562430e+00,  1.00000000e+00,
        -8.16496581e-01,  1.22474487e+00,  1.22474487e+00,
        -1.52752523e+00, -3.33333333e-01, -5.00000000e-01,
         3.00000000e+00],
       [-9.48757423e-01, -9.57679776e-01,  1.00000000e+00,
        -8.16496581e-01, -8.16496581e-01,  1.22474487e+00,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [ 1.00805476e+00,  1.54690159e+00, -1.00000000e+00,
        -8.16496581e-01,  1.22474487e+00, -8.16496581e-01,
        -1.52752523e+00, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [ 6.52270728e-01, -3.28036417e-01, -1.00000000e+00,
         1.22474487e+00, -8.16496581e-01, -8.16496581e-01,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.33333333e-01],
       [-1.30454146e+00, -2.03611484e-16, -1.00000000e+00,
         1.22474487e+00, -8.16496581e-01, -8.16496581e-01,
         6.54653671e-01, -3.33333333e-01, -5.00000000e-01,
        -3.

# An alternative standardization is scaling features to lie between a given minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size. This can be achieved using MinMaxScaler.


In [46]:
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(x)
X_minmax

array([[0.        , 0.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 0.        , 0.        , 1.        ],
       [0.11111111, 0.03153153, 1.        , 0.        , 0.        ,
        1.        , 1.        , 0.        , 0.        , 0.        ],
       [0.72222222, 0.83783784, 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.61111111, 0.23423423, 0.        , 1.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.33983984, 0.        , 1.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.41441441, 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ],
       [0.40740741, 1.        , 1.        , 0.        , 1.        ,
        1.        , 1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.0990991 , 1.       

In [ ]:
A cleaned dataset to some extent